### ISSUE TITLE
Does the patch do anything other than extract Littlewitch.exe and LWSystem.dat?

### ISSUE THREAD

**Issue by steinuil** [ItaloKnox/littlewitch#2]
Hey, I wanted to use the patch on the Steam Deck, I tried installing it to an empty folder and it looks like it just creates a bunch of empty directories and copies Littlewitch.exe and LWSystem.dat. I tried copying those files to the deck and it looks like it boots up fine.

Does it do anything other than copying those two files? It doesn't seem to make any changes to the registry or anything of the sort so I was thinking to just put those two in a zip file to make it easier for Linux users to install without messing with Proton or Wine.

If that's the case would you accept a PR to the README just to say that it does work on Linux/Proton if you overwrite those files and add the zip file to the release page? Thanks!

**Comment by ItaloKnox** [comment]
Hi! I haven't touched this repo in a thousand years, and looking back at it, it's far less than ideal in how it's supposed to be usually handled. I don't think it really does more than those two files. The empty folders were a limitation from the installation process, I think?

You don't have to PR the changes, I'll edit the release to add your findings. Thanks!

**Comment by steinuil** [comment]
Thank you!
